{{- if and .Values.experimentation.enabled .Values.hpa.ingestion.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ include "flagsmith.namespace" . }}
  name: {{ include "flagsmith.fullname" . }}-ingestion
  labels:
    {{- include "flagsmith.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "flagsmith.fullname" . }}-ingestion
  minReplicas: {{ .Values.hpa.ingestion.minReplicas }}
  maxReplicas: {{ .Values.hpa.ingestion.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.ingestion.targetCPUUtilization }}
{{- end }}
