{{- if and .Values.experimentation.enabled .Values.ingress.ingestion.enabled }}
{{- $fullName := include "flagsmith.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ include "flagsmith.namespace" . }}
  name: {{ $fullName }}-ingestion
  labels:
    {{- include "flagsmith.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
  {{- with include "flagsmith.annotations" (dict "customAnnotations" .Values.ingress.ingestion.annotations "commonValues" .Values.common) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.ingestion.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.ingestion.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.ingestion.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-ingestion
                port:
                  number: {{ $.Values.service.ingestion.port }}
          {{- end }}
    {{- end }}
{{- end }}
