{{- if .Values.experimentation.enabled }}
{{- include "flagsmith.experimentation.validate" . }}
{{- $e := .Values.experimentation }}
{{- $data := dict }}
{{- if not $e.clickhouse.urlFromExistingSecret.enabled }}
{{- $_ := set $data "CLICKHOUSE_URL" $e.clickhouse.url }}
{{- end }}
{{- if and (eq $e.kafka.auth "scram") (not $e.kafka.passwordFromExistingSecret.enabled) }}
{{- $_ := set $data "KAFKA_PASSWORD" $e.kafka.password }}
{{- end }}
{{- with $data }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "flagsmith.namespace" $ }}
  name: {{ include "flagsmith.experimentation.secretName" $ }}
  labels:
    {{- include "flagsmith.labels" $ | nindent 4 }}
    app.kubernetes.io/component: experimentation
type: Opaque
data:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
