{{- if .Values.hooks.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "bullettrain.fullname" . }}-api-migrate
  labels:
    app: {{ template "bullettrain.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "{{ if .Values.hooks.removeOnSuccess }}hook-succeeded,{{ end }}before-hook-creation"
    "helm.sh/hook-weight": "5"
spec:
  template:
    metadata:
      name: {{ template "bullettrain.fullname" . }}-api-migrate
      labels:
        app: {{ template "bullettrain.fullname" . }}-api-migrate
        release: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
      - name: api-migrate
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        command:
          - /bin/bash
          - -ec
          - >-
            pipenv run python manage.py migrate --noinput &&
            pipenv run python manage.py collectstatic --noinput
        env:
        - name: DJANGO_DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ template "bullettrain.fullname" . }}
              key: dbname
        - name: DJANGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "bullettrain.fullname" . }}
              key: dbuser
        - name: DJANGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "bullettrain.fullname" . }}
              key: dbpassword
        - name: DJANGO_DB_PORT
          value: "5432"
        - name: DJANGO_DB_HOST
          value: {{ include "bullettrain.postgresql.host" . | quote }}
{{- end }}