{{- if .Values.hpa.taskProcessor.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "flagsmith.fullname" . }}-task-processor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "flagsmith.fullname" . }}-task-processor
  minReplicas: {{ .Values.hpa.taskProcessor.minReplicas }}
  maxReplicas: {{ .Values.hpa.taskProcessor.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.taskProcessor.targetCPUUtilization }}
{{- end }}
