{{- if .Values.gateway.api.enabled -}}
{{- $fullName := include "flagsmith.fullname" . -}}
{{- $svcPort := .Values.service.api.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ include "flagsmith.namespace" . }}
  name: {{ $fullName }}-api
  labels:
    {{- include "flagsmith.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- $annotations := include "flagsmith.annotations" ( dict "customAnnotations" .Values.gateway.annotations "commonValues" .Values.common ) }}
  {{- with $annotations }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.gateway.api.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.api.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  # TODO: add default rules for /api/, /health/, /admin/, /static/admin/
  rules:
    {{- toYaml .Values.gateway.api.rules | nindent 4 }}
{{- end }}
