{{- if .Values.pdb.api.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "flagsmith.fullname" . }}-api-pdb
  labels:
    {{- include "flagsmith.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    matchLabels:
      {{- include "flagsmith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  {{- if hasKey .Values.pdb.api "maxUnavailable" }}
  maxUnavailable: {{ .Values.pdb.api.maxUnavailable }}
  {{- else if hasKey .Values.pdb.api "minAvailable" }}
  minAvailable: {{ .Values.pdb.api.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.api.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ .Values.pdb.api.unhealthyPodEvictionPolicy }}
  {{- end }}
{{- end }}
