{{- if .Values.pdb.api.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "flagsmith.fullname" . }}-api-pdb
spec:
  selector:
    matchLabels:
      {{- include "flagsmith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  {{- if and .Values.pdb.api.minAvailable (not (hasKey .Values.pdb.api "maxUnavailable")) }}
  minAvailable: {{ .Values.pdb.api.minAvailable }}
  {{- else if .Values.pdb.api.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.api.maxUnavailable }}
  {{- end }}
  {{- if .Values.pdb.api.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ .Values.pdb.api.unhealthyPodEvictionPolicy }}
  {{- end }}
{{- end }}
