{{- if .Values.influxdb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
  name: {{ template "influxdb.fullname" . }}-auth
data:
  {{- if .Values.influxdb.adminUser.token }}
  admin-token: {{ .Values.influxdb.adminUser.token | b64enc | quote }}
  {{- else }}
  admin-token: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.influxdb.adminUser.password }}
  admin-password: {{ .Values.influxdb.adminUser.password | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
