apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flagsmith.fullname" . }}-sse
  {{- $annotations := include "flagsmith.annotations" .Values.common }}
  {{- with $annotations }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "flagsmith.labels" . | nindent 4 }}
    app.kubernetes.io/component: sse
type: Opaque
stringData:
  SSE_AUTHENTICATION_TOKEN: {{ include "flagsmith.sse.authenticationToken" . | quote }}