{{- if and .Values.sse.enabled (not .Values.sse.authenticationTokenFromExistingSecret.enabled) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "flagsmith.sse.authenticationTokenSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flagsmith.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "flagsmith.sse.authenticationTokenSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flagsmith.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "flagsmith.sse.authenticationTokenSecretName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "flagsmith.sse.authenticationTokenSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
