{{- if and .Values.sse.enabled (not .Values.api.secretKeyFromExistingSecret.enabled) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flagsmith.fullname" . }}-django-secret-init
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "flagsmith.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}
